fix: deployment workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,7 +20,7 @@ jobs:
           curl -H "Content-Type: application/json" -X POST -d '{"content":"🚀 Starting deployment..."}' $DISCORD_WEBHOOK_URL
 
       - name: Checkout Code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Install SSHPass
         run: sudo apt-get install -y sshpass
@@ -97,6 +97,19 @@ jobs:
             echo "SQL Server Docker container status: $(docker ps --format "{{.Status}}" --filter "name=sfcm-db")"
             # Run the deploy script
             /root/capstone-new/SFCM_FE/deployment/deploy.sh
+
+            # Check if all required containers are running
+            missing_containers=""
+            for container in sfcm-db sfcm-fe sfcm-be; do
+              if [ "$(docker ps -q -f name=$container)" == "" ]; then
+                missing_containers="$missing_containers $container"
+              fi
+            done
+
+            if [ "$missing_containers" != "" ]; then
+              echo "The following containers are not running: $missing_containers"
+              exit 1
+            fi
           EOF
 
       - name: Notify Discord Deployment Success
